-- ============================================
-- COMPLETE DATABASE SETUP - ALL DOMAINS
-- Drop old tables and recreate with TEXT user_id
-- ============================================

-- Drop existing tables
DROP TABLE IF EXISTS myntra_data CASCADE;
DROP TABLE IF EXISTS ajio_data CASCADE;
DROP TABLE IF EXISTS flipkart_data CASCADE;
DROP TABLE IF EXISTS amazon_data CASCADE;

-- ============================================
-- MYNTRA TABLE
-- ============================================
CREATE TABLE myntra_data (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  seller_order_id TEXT,
  seller_sku_code TEXT,
  size TEXT,
  seller_id TEXT,
  warehouse_id TEXT,
  seller_warehouse_id TEXT,
  po_type TEXT,
  store_order_id TEXT,
  order_release_id TEXT,
  order_line_id TEXT,
  order_id_fk TEXT,
  created_on TIMESTAMP,
  order_status TEXT,
  style_id TEXT,
  sku_id TEXT,
  myntra_sku_code TEXT,
  vendor_article_number TEXT,
  brand TEXT,
  style_name TEXT,
  article_type TEXT,
  final_amount DECIMAL(12, 2),
  total_mrp DECIMAL(12, 2),
  discount DECIMAL(12, 2),
  coupon_discount DECIMAL(12, 2),
  shipping_charge DECIMAL(12, 2),
  gift_charge DECIMAL(12, 2),
  tax_recovery DECIMAL(12, 2),
  packet_id TEXT,
  seller_packet_id TEXT,
  courier_code TEXT,
  order_tracking_number TEXT,
  packed_on TIMESTAMP,
  fmpu_date TIMESTAMP,
  inscanned_on TIMESTAMP,
  shipped_on TIMESTAMP,
  delivered_on TIMESTAMP,
  cancelled_on TIMESTAMP,
  rto_creation_date TIMESTAMP,
  lost_date TIMESTAMP,
  return_creation_date TIMESTAMP,
  cancellation_reason_id_fk TEXT,
  cancellation_reason TEXT,
  city TEXT,
  state TEXT,
  zipcode TEXT,
  raw_data JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, seller_order_id, seller_sku_code, size)
);

CREATE INDEX idx_myntra_user_id ON myntra_data(user_id);
CREATE INDEX idx_myntra_seller_order_id ON myntra_data(seller_order_id);
CREATE INDEX idx_myntra_created_on ON myntra_data(created_on);
CREATE INDEX idx_myntra_order_status ON myntra_data(order_status);

ALTER TABLE myntra_data DISABLE ROW LEVEL SECURITY;

-- ============================================
-- AJIO TABLE
-- ============================================
CREATE TABLE ajio_data (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  sale_order_code TEXT,
  item_code TEXT,
  order_date TIMESTAMP,
  sale_order_status TEXT,
  on_hold BOOLEAN,
  priority TEXT,
  sku_name TEXT,
  seller_sku_code TEXT,
  item_code_value TEXT,
  combination_identifier TEXT,
  combination_description TEXT,
  mrp DECIMAL(12, 2),
  total_price DECIMAL(12, 2),
  selling_price DECIMAL(12, 2),
  cost_price DECIMAL(12, 2),
  discount DECIMAL(12, 2),
  voucher_code TEXT,
  transfer_price DECIMAL(12, 2),
  gst_tax_type_code TEXT,
  cgst DECIMAL(12, 2),
  igst DECIMAL(12, 2),
  sgst DECIMAL(12, 2),
  utgst DECIMAL(12, 2),
  cess DECIMAL(12, 2),
  cgst_rate DECIMAL(5, 2),
  igst_rate DECIMAL(5, 2),
  sgst_rate DECIMAL(5, 2),
  utgst_rate DECIMAL(5, 2),
  cess_rate DECIMAL(5, 2),
  tcs_amount DECIMAL(12, 2),
  tax_percent DECIMAL(5, 2),
  tax_value DECIMAL(12, 2),
  shipping_charges DECIMAL(12, 2),
  shipping_method_charges DECIMAL(12, 2),
  cod_service_charges DECIMAL(12, 2),
  gift_wrap_charges DECIMAL(12, 2),
  shipping_provider TEXT,
  shipping_courier TEXT,
  shipping_arranged_by TEXT,
  shipping_package_code TEXT,
  shipping_package_creation_date TIMESTAMP,
  shipping_package_status_code TEXT,
  shipping_package_type TEXT,
  tracking_number TEXT,
  dispatch_date TIMESTAMP,
  delivery_time TEXT,
  sale_order_item_status TEXT,
  cancellation_reason TEXT,
  return_date TIMESTAMP,
  return_reason TEXT,
  return_remarks TEXT,
  facility TEXT,
  packet_number TEXT,
  imei TEXT,
  weight DECIMAL(10, 2),
  hsn_code TEXT,
  gstin TEXT,
  customer_gstin TEXT,
  tin TEXT,
  payment_instrument TEXT,
  batch_code TEXT,
  vendor_batch_number TEXT,
  item_type_ean TEXT,
  item_seal_id TEXT,
  parent_sale_order_code TEXT,
  item_tag TEXT,
  shipment_tag TEXT,
  gift_wrap TEXT,
  gift_message TEXT,
  prepaid_amount DECIMAL(12, 2),
  subtotal DECIMAL(12, 2),
  store_credit DECIMAL(12, 2),
  irn TEXT,
  acknowledgement_number TEXT,
  bundle_sku_code_number TEXT,
  currency TEXT,
  currency_conversion_rate DECIMAL(10, 4),
  fulfillment_tat TEXT,
  adjustment_in_selling_price DECIMAL(12, 2),
  adjustment_in_discount DECIMAL(12, 2),
  shipping_courier_status TEXT,
  shipping_tracking_status TEXT,
  cashfree TEXT,
  tags TEXT,
  channel_shipping TEXT,
  item_details TEXT,
  raw_data JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, sale_order_code, item_code)
);

CREATE INDEX idx_ajio_user_id ON ajio_data(user_id);
CREATE INDEX idx_ajio_sale_order_code ON ajio_data(sale_order_code);
CREATE INDEX idx_ajio_order_date ON ajio_data(order_date);
CREATE INDEX idx_ajio_status ON ajio_data(sale_order_status);

ALTER TABLE ajio_data DISABLE ROW LEVEL SECURITY;

-- ============================================
-- FLIPKART TABLE
-- ============================================
CREATE TABLE flipkart_data (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  sale_order_code TEXT,
  item_sku_code TEXT,
  sale_order_item_code TEXT,
  display_order_code TEXT,
  order_date TIMESTAMP,
  sale_order_status TEXT,
  on_hold BOOLEAN,
  priority TEXT,
  reverse_pickup_code TEXT,
  reverse_pickup_created_date TIMESTAMP,
  reverse_pickup_reason TEXT,
  notification_email TEXT,
  notification_mobile TEXT,
  require_customization BOOLEAN,
  sku_require_customization BOOLEAN,
  cod BOOLEAN,
  shipping_address_id TEXT,
  shipping_address_name TEXT,
  shipping_address_line_1 TEXT,
  shipping_address_line_2 TEXT,
  shipping_address_city TEXT,
  shipping_address_state TEXT,
  shipping_address_country TEXT,
  shipping_address_pincode TEXT,
  shipping_address_latitude DECIMAL(10, 8),
  shipping_address_longitude DECIMAL(11, 8),
  shipping_address_phone TEXT,
  billing_address_id TEXT,
  billing_address_name TEXT,
  billing_address_line_1 TEXT,
  billing_address_line_2 TEXT,
  billing_address_city TEXT,
  billing_address_state TEXT,
  billing_address_country TEXT,
  billing_address_pincode TEXT,
  billing_address_latitude DECIMAL(10, 8),
  billing_address_longitude DECIMAL(11, 8),
  billing_address_phone TEXT,
  shipping_method TEXT,
  item_code TEXT,
  channel_product_id TEXT,
  item_type_name TEXT,
  item_type_color TEXT,
  item_type_size TEXT,
  item_type_brand TEXT,
  channel_name TEXT,
  sku_name TEXT,
  category TEXT,
  mrp DECIMAL(12, 2),
  total_price DECIMAL(12, 2),
  selling_price DECIMAL(12, 2),
  cost_price DECIMAL(12, 2),
  discount DECIMAL(12, 2),
  prepaid_amount DECIMAL(12, 2),
  subtotal DECIMAL(12, 2),
  voucher_code TEXT,
  transfer_price DECIMAL(12, 2),
  gst_tax_type_code TEXT,
  cgst DECIMAL(12, 2),
  igst DECIMAL(12, 2),
  sgst DECIMAL(12, 2),
  utgst DECIMAL(12, 2),
  cess DECIMAL(12, 2),
  cgst_rate DECIMAL(5, 2),
  igst_rate DECIMAL(5, 2),
  sgst_rate DECIMAL(5, 2),
  utgst_rate DECIMAL(5, 2),
  cess_rate DECIMAL(5, 2),
  tcs_amount DECIMAL(12, 2),
  tax_percent DECIMAL(5, 2),
  tax_value DECIMAL(12, 2),
  shipping_charges DECIMAL(12, 2),
  shipping_method_charges DECIMAL(12, 2),
  cod_service_charges DECIMAL(12, 2),
  gift_wrap_charges DECIMAL(12, 2),
  shipping_provider TEXT,
  shipping_courier TEXT,
  shipping_arranged_by TEXT,
  shipping_package_code TEXT,
  shipping_package_creation_date TIMESTAMP,
  shipping_package_status_code TEXT,
  shipping_package_type TEXT,
  tracking_number TEXT,
  dispatch_date TIMESTAMP,
  facility TEXT,
  delivery_time TEXT,
  length_mm DECIMAL(10, 2),
  width_mm DECIMAL(10, 2),
  height_mm DECIMAL(10, 2),
  weight DECIMAL(10, 2),
  sale_order_item_status TEXT,
  cancellation_reason TEXT,
  return_date TIMESTAMP,
  return_reason TEXT,
  return_remarks TEXT,
  invoice_code TEXT,
  invoice_created TIMESTAMP,
  eway_bill_no TEXT,
  eway_bill_date TIMESTAMP,
  eway_bill_valid_till TIMESTAMP,
  gift_wrap TEXT,
  gift_message TEXT,
  payment_instrument TEXT,
  store_credit DECIMAL(12, 2),
  hsn_code TEXT,
  gstin TEXT,
  customer_gstin TEXT,
  tin TEXT,
  irn TEXT,
  acknowledgement_number TEXT,
  bundle_sku_code_number TEXT,
  batch_code TEXT,
  vendor_batch_number TEXT,
  seller_sku_code TEXT,
  item_type_ean TEXT,
  imei TEXT,
  fulfillment_tat TEXT,
  adjustment_in_selling_price DECIMAL(12, 2),
  adjustment_in_discount DECIMAL(12, 2),
  shipping_courier_status TEXT,
  shipping_tracking_status TEXT,
  packet_number TEXT,
  item_seal_id TEXT,
  parent_sale_order_code TEXT,
  item_tag TEXT,
  shipment_tag TEXT,
  cashfree TEXT,
  tags TEXT,
  channel_shipping TEXT,
  item_details TEXT,
  currency TEXT,
  currency_conversion_rate DECIMAL(10, 4),
  raw_data JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, sale_order_code, item_sku_code)
);

CREATE INDEX idx_flipkart_user_id ON flipkart_data(user_id);
CREATE INDEX idx_flipkart_sale_order_code ON flipkart_data(sale_order_code);
CREATE INDEX idx_flipkart_order_date ON flipkart_data(order_date);
CREATE INDEX idx_flipkart_status ON flipkart_data(sale_order_status);
CREATE INDEX idx_flipkart_city ON flipkart_data(shipping_address_city);

ALTER TABLE flipkart_data DISABLE ROW LEVEL SECURITY;

-- ============================================
-- AMAZON TABLE
-- ============================================
CREATE TABLE amazon_data (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  sale_order_code TEXT,
  item_sku_code TEXT,
  sale_order_item_code TEXT,
  display_order_code TEXT,
  order_date TIMESTAMP,
  sale_order_status TEXT,
  on_hold BOOLEAN,
  priority TEXT,
  reverse_pickup_code TEXT,
  reverse_pickup_created_date TIMESTAMP,
  reverse_pickup_reason TEXT,
  notification_email TEXT,
  notification_mobile TEXT,
  require_customization BOOLEAN,
  sku_require_customization BOOLEAN,
  cod BOOLEAN,
  shipping_address_id TEXT,
  shipping_address_name TEXT,
  shipping_address_line_1 TEXT,
  shipping_address_line_2 TEXT,
  shipping_address_city TEXT,
  shipping_address_state TEXT,
  shipping_address_country TEXT,
  shipping_address_pincode TEXT,
  shipping_address_latitude DECIMAL(10, 8),
  shipping_address_longitude DECIMAL(11, 8),
  shipping_address_phone TEXT,
  billing_address_id TEXT,
  billing_address_name TEXT,
  billing_address_line_1 TEXT,
  billing_address_line_2 TEXT,
  billing_address_city TEXT,
  billing_address_state TEXT,
  billing_address_country TEXT,
  billing_address_pincode TEXT,
  billing_address_latitude DECIMAL(10, 8),
  billing_address_longitude DECIMAL(11, 8),
  billing_address_phone TEXT,
  shipping_method TEXT,
  item_code TEXT,
  channel_product_id TEXT,
  item_type_name TEXT,
  item_type_color TEXT,
  item_type_size TEXT,
  item_type_brand TEXT,
  channel_name TEXT,
  sku_name TEXT,
  category TEXT,
  mrp DECIMAL(12, 2),
  total_price DECIMAL(12, 2),
  selling_price DECIMAL(12, 2),
  cost_price DECIMAL(12, 2),
  discount DECIMAL(12, 2),
  prepaid_amount DECIMAL(12, 2),
  subtotal DECIMAL(12, 2),
  voucher_code TEXT,
  transfer_price DECIMAL(12, 2),
  gst_tax_type_code TEXT,
  cgst DECIMAL(12, 2),
  igst DECIMAL(12, 2),
  sgst DECIMAL(12, 2),
  utgst DECIMAL(12, 2),
  cess DECIMAL(12, 2),
  cgst_rate DECIMAL(5, 2),
  igst_rate DECIMAL(5, 2),
  sgst_rate DECIMAL(5, 2),
  utgst_rate DECIMAL(5, 2),
  cess_rate DECIMAL(5, 2),
  tcs_amount DECIMAL(12, 2),
  tax_percent DECIMAL(5, 2),
  tax_value DECIMAL(12, 2),
  shipping_charges DECIMAL(12, 2),
  shipping_method_charges DECIMAL(12, 2),
  cod_service_charges DECIMAL(12, 2),
  gift_wrap_charges DECIMAL(12, 2),
  shipping_provider TEXT,
  shipping_courier TEXT,
  shipping_arranged_by TEXT,
  shipping_package_code TEXT,
  shipping_package_creation_date TIMESTAMP,
  shipping_package_status_code TEXT,
  shipping_package_type TEXT,
  tracking_number TEXT,
  dispatch_date TIMESTAMP,
  facility TEXT,
  delivery_time TEXT,
  length_mm DECIMAL(10, 2),
  width_mm DECIMAL(10, 2),
  height_mm DECIMAL(10, 2),
  weight DECIMAL(10, 2),
  sale_order_item_status TEXT,
  cancellation_reason TEXT,
  return_date TIMESTAMP,
  return_reason TEXT,
  return_remarks TEXT,
  invoice_code TEXT,
  invoice_created TIMESTAMP,
  eway_bill_no TEXT,
  eway_bill_date TIMESTAMP,
  eway_bill_valid_till TIMESTAMP,
  gift_wrap TEXT,
  gift_message TEXT,
  payment_instrument TEXT,
  store_credit DECIMAL(12, 2),
  hsn_code TEXT,
  gstin TEXT,
  customer_gstin TEXT,
  tin TEXT,
  irn TEXT,
  acknowledgement_number TEXT,
  bundle_sku_code_number TEXT,
  batch_code TEXT,
  vendor_batch_number TEXT,
  seller_sku_code TEXT,
  item_type_ean TEXT,
  imei TEXT,
  fulfillment_tat TEXT,
  adjustment_in_selling_price DECIMAL(12, 2),
  adjustment_in_discount DECIMAL(12, 2),
  shipping_courier_status TEXT,
  shipping_tracking_status TEXT,
  packet_number TEXT,
  item_seal_id TEXT,
  parent_sale_order_code TEXT,
  item_tag TEXT,
  shipment_tag TEXT,
  cashfree TEXT,
  tags TEXT,
  channel_shipping TEXT,
  item_details TEXT,
  currency TEXT,
  currency_conversion_rate DECIMAL(10, 4),
  raw_data JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, sale_order_code, item_sku_code)
);

CREATE INDEX idx_amazon_user_id ON amazon_data(user_id);
CREATE INDEX idx_amazon_sale_order_code ON amazon_data(sale_order_code);
CREATE INDEX idx_amazon_order_date ON amazon_data(order_date);
CREATE INDEX idx_amazon_status ON amazon_data(sale_order_status);
CREATE INDEX idx_amazon_city ON amazon_data(shipping_address_city);

ALTER TABLE amazon_data DISABLE ROW LEVEL SECURITY;

-- ============================================
-- VERIFY SETUP
-- ============================================
-- Check all tables created correctly
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN ('myntra_data', 'ajio_data', 'flipkart_data', 'amazon_data');

-- Check user_id column type (should be TEXT)
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name IN ('myntra_data', 'ajio_data', 'flipkart_data', 'amazon_data')
  AND column_name = 'user_id'
ORDER BY table_name;
